### ISSUE TITLE
Select data table library

### ISSUE THREAD

**Issue by rjzupkoii** [alexGalushka/CapStone_HES_2015#9]

**Comment by ibugarinovic** [comment]
There are three most used Angular plugins for data grid:
Smart table
ng-grid
ng-table

Smart table has several advantages:

It’s lightweight: 4K minified
It is pure Angular solution, no dependencies other than Angular itself 
It’s easy to configure and customize
Table is composed in declarative way, similar to HTML
It can be extended with plugins
There are features that we need in our project:

User have full control of data and cell formats 

Sort data is built in, it’s declarative, and you may specify function for sort

Search can be done globally, by column, or through predicates

It has select and multiselect row option

Built in pagination on client side

It can sync display data with underlying base data operated through remote calls.

Pipe/ajax plug allows user to override basic display table operation and call server instead.

You can add your own plug in, there are several examples and ready to use how you create: draggable headers, pagination on scroll, fix headers, or custom pagination.

It uses regular html tags for tables and the standard ng-repeat for the rows and standard bootstrap for formatting. You can easily add plug in if you need.

There are more features in other plugins but it’s not easily customizable, and there are reviews claiming it’s full of bugs that are ignored.  

This is is link for Smart table (you can find link to other two grid plugins):

http://lorenzofox3.github.io/smart-table-website/


I think it’s best choice because it follows Angular way of developing pages, you can insert table in minutes. It covers all our requirements and after the second Milestone we can add any other feature. I did test it, and it worked without any issue.
